# .github/workflows/dummy.yml
name: Dummy action

on:
  workflow_dispatch:

jobs:
  dummy-job:
    runs-on: [self-hosted, Linux]
    steps:
      - name: say hello
        run: |
          echo hello, world!
